# Spring properties
spring:
  application:
    name: authorisation-service
  
# JWT certificate
certificate:
  filename: jwt.jks
  password: mySecretKey
  keyPair: jwt
  
# Client details
client:
  name: fooClientIdPassword
  password: fred

# Discovery Server Access
#eureka:
 # client:
 #   serviceUrl: 
 #     defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 3333   # HTTP (Tomcat) port
 # ssl:
 #   enabled: true
 #   key-alias: animalea
 #   key-store: src/main/resources/leasslkeystore.p12
 #   key-store-type: PKCS12
 #   key-store-password: password
 #   key-password: password